<a href="https://colab.research.google.com/github/Adityeah18/tensorflow/blob/main/module-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module-1

### Some Theory:

- **Machine Learning (ML)** is a subset of **Artificial Intelligence (AI)**.
- **AI** works based on defined rules.
- **ML** allows the system to define rules by learning from data using techniques like **Deep Learning**.
- **Deep Learning** occurs between layers in what is known as a **Neural Network**.

---

## Types of Data in Machine Learning

- **Features**: The inputs used to make predictions.
- **Labels**: The outputs the model is trying to predict.

---

## Types of Learning

### 1. Supervised Learning
- Requires a large dataset containing both **features** and **labels**.
- The model learns from these labeled examples to make predictions on new, unseen data.

### 2. Unsupervised Learning
- Uses **features** only; no labeled output.
- The model attempts to identify patterns or groupings within the data.
- Example: **K-means clustering**

### 3. Reinforcement Learning
- Involves training an **agent** through **rewards** and **penalties**.
- There is no dataset; learning happens through interaction with an environment.
- Correct actions are rewarded, and incorrect ones are penalized.
- Example: training a robot through trial and error.


## TensorFlow

### What is a Tensor?

- TensorFlow is a machine learning library maintained by **Google**.
- **Tensors** are multi-dimensional arrays (like vectors and matrices) that hold data.
- In TensorFlow, tensors are partially defined data structures which we manipulate to optimize outcomes such as **accuracy**, **precision**, or **loss**.






In [61]:
import tensorflow as tf

# Example to demonstrate tensor ranks (degrees)

# Rank 1 Tensor (1D): A single list of strings
rank1_tensor = tf.Variable(["Test"], tf.string)

# Rank 2 Tensor (2D): A matrix (list of lists) of strings
rank2_tensor = tf.Variable([["Test2", "OK"],["Test2", "OK"]], tf.string)

# Check and print the rank (number of dimensions) of the tensors
print("Rank of rank1_tensor:", tf.rank(rank1_tensor))  # Output: 1
print("Rank of rank2_tensor:", tf.rank(rank2_tensor))  # Output: 2


Rank of rank1_tensor: tf.Tensor(1, shape=(), dtype=int32)
Rank of rank2_tensor: tf.Tensor(2, shape=(), dtype=int32)


## Shapes of Tensors:
### Shape

- **Shape** represents the **dimensions** of the data.
- Example: A shape of `(3, 4)` means 3 rows and 4 columns (like a 2D matrix).

---

### Rank (or Degree)

- **Rank** refers to the **number of dimensions** a tensor has.
- Examples:
  - `[]` → Scalar → **Rank 0**
  - `[1, 2, 3]` → Vector → **Rank 1**
  - `[[1, 2], [3, 4]]` → Matrix → **Rank 2**

The **shape** of a tensor defines how many elements exist across each dimension (axis) of the tensor. It helps us understand the structure of data stored inside.

Think of it as:

- The number of rows and columns (and more, if higher-dimensional) in the tensor.
- It tells how many values are present in each vector or in the innermost brackets.


#### Examples:

- A 1D tensor like: `["hello", "world"]` has shape `(2,)`
- A 2D tensor like: `[["hi", "there"], ["ok", "sure"]]` has shape `(2, 2)`
- A 3D tensor like: `[[["a"], ["b"]], [["c"], ["d"]]]` has shape `(2, 2, 1)`


In [62]:
print(f'Rank1 {rank1_tensor.shape}')
print(f'Rank2 {rank2_tensor.shape}' )

Rank1 (1,)
Rank2 (2, 2)


###Changing the shapes

In [63]:
tensor1=tf.Variable([2],tf,int)
#tf.rank(tensor1)
tensor2=tf.ones([1,2,3])
#tf.rank(tensor2)#Rank/Degree of tensor 2 = 3
#tensor2.shape #Shape= TensorShape([1, 2, 3])

#Reshaping
tensor2_reshaped= tf.reshape(tensor2,[3,2,1])
#print(tensor2_reshaped)
#tf.rank(tensor2_reshaped)

# Assuming tensor2_reshaped has shape (3, 2, 1) and 6 total elements
tensor_reshaped = tf.reshape(tensor2_reshaped, [3, -1])

# TensorFlow will calculate the second dimension:
# total_elements = 6
# first_dimension = 3
# second_dimension = total_elements / first_dimension = 6 / 3 = 2

# Therefore, tensor_reshaped will have shape (3, 2)

print(tensor_reshaped)
tf.rank(tensor_reshaped) #How the dree change to 2??

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Slice of Tensors
Slice can be used in python in lists and tuples but it can also be used in tensorflow
In tensorflow it is used in selecting some particular element of any vector
In TensorFlow, slicing helps us access specific elements or subsets of data inside tensors. It is especially useful when dealing with batches, time steps, or any structured tensor data.

In [64]:
#Creating the 2d Tensor
matrix=[[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]]
tensor=tf.Variable(matrix,tf.int32) #int32 is the datatype used in tf as for int in pythoh
print(tf.rank(tensor)) #<tf.Tensor: shape=(), dtype=int32, numpy=2>
print(tensor.shape) #TensorShape([4, 5])


tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [65]:
#Let's select the vector(slicing from out matrix)
#Remember python index starts with 0

#slecting row 1 element 3
element_three=tensor[0,2] #
print(element_three)# 3

row1=tensor[0]#[1,2,3,4,5]
print(row1)

#tensor[start_index : end_index]
column2=tensor[:,1]
print(column2) #[ 2  7 12 17]

#tensor[start_row:end_row, start_col:end_col]

row2_and_row4=tensor[1:3]
print(row2_and_row4)#[ 6  7  8  9 10]
                    #[11 12 13 14 15]

col1_in_row2_and_row3=tensor[1:2,0]
print(col1_in_row2_and_row3)# [ 6  7  8  9 10]
                             #[11 12 13 14 15]



tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 2  7 12 17], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [11 12 13 14 15]], shape=(2, 5), dtype=int32)
tf.Tensor([6], shape=(1,), dtype=int32)
